// src/presentation-react/components/Hotkeys.jsx
import React, { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { toggleHelp } from '../../app/slices/uiSlice.js'
import { fitToAll, fitToSelection, resetView } from '../../app/slices/viewerSlice.js'
import { isolateSection, clearIsolation } from '../../app/slices/modelSlice.js'

function isTypingTarget(t) {
  if (!t) return false
  const tag = (t.tagName || '').toLowerCase()
  return tag === 'input' || tag === 'textarea' || t.isContentEditable
}

export default function Hotkeys () {
  const dispatch = useDispatch()
  const helpVisible = useSelector(s => s.ui.help.visible)
  const selected = useSelector(s => s.model.selectedNodeId)
  const isolated = useSelector(s => s.model.isolatedNodeId)

  useEffect(() => {
    const onKeyDown = (e) => {
      if (isTypingTarget(e.target)) return
      const key = e.key
      if ((key === '?' || (key === '/' && e.shiftKey))) {
        e.preventDefault()
        dispatch(toggleHelp())
        return
      }
      if (key === 'f' || key === 'F') {
        e.preventDefault()
        if (selected) dispatch(fitToSelection())
        else dispatch(fitToAll())
        return
      }
      if (key === 'a' || key === 'A') {
        e.preventDefault()
        dispatch(fitToAll())
        return
      }
      if (key === 'i' || key === 'I') {
        if (selected) {
          e.preventDefault()
          dispatch(isolateSection({ nodeId: selected }))
        }
        return
      }
      if (key === 'Escape' || key === 'e' || key === 'E') {
        if (isolated) {
          e.preventDefault()
          dispatch(clearIsolation())
        }
        return
      }
      if (key === 'r' || key === 'R') {
        e.preventDefault()
        dispatch(resetView())
        return
      }
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [dispatch, selected, isolated])

  if (!helpVisible) return null
  return (
    <div className='overlay' style={{ left: 12, top: 56, right: 'auto' }}>
      <div style={{ fontWeight: 600, marginBottom: 6 }}>Shortcuts</div>
      <div>?: Toggle help</div>
      <div>F: Fit selection (or all)</div>
      <div>A: Fit all</div>
      <div>I: Isolate selection</div>
      <div>Esc: Clear isolation</div>
      <div>R: Reset view</div>
    </div>
  )
}

// src/app/components/hotkeys/hotkeys.component.ts
import { Component, OnInit, OnDestroy, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subject, takeUntil } from 'rxjs';
import { UIService, UIState } from '../../services/ui.service';
import { ViewerService } from '../../services/viewer.service';
import { ModelService, ModelState } from '../../services/model.service';

@Component({
  selector: 'app-hotkeys',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (helpVisible) {
      <div class="overlay" style="left: 12px; top: 56px; right: auto;">
        <div style="font-weight: 600; margin-bottom: 6px;">Shortcuts</div>
        <div>?: Toggle help</div>
        <div>F: Fit selection (or all)</div>
        <div>A: Fit all</div>
        <div>I: Isolate selection</div>
        <div>Esc: Clear isolation</div>
        <div>R: Reset view</div>
      </div>
    }
  `,
  styles: []
})
export class HotkeysComponent implements OnInit, OnDestroy {
  helpVisible = false;
  selectedNodeId: string | null = null;
  isolatedNodeId: string | null = null;
  private destroy$ = new Subject<void>();

  constructor(
    private uiService: UIService,
    private viewerService: ViewerService,
    private modelService: ModelService
  ) {}

  ngOnInit(): void {
    this.uiService.state$
      .pipe(takeUntil(this.destroy$))
      .subscribe((state: UIState) => {
        this.helpVisible = state.help.visible;
      });

    this.modelService.state$
      .pipe(takeUntil(this.destroy$))
      .subscribe((state: ModelState) => {
        this.selectedNodeId = state.selectedNodeId;
        this.isolatedNodeId = state.isolatedNodeId;
      });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  @HostListener('window:keydown', ['$event'])
  handleKeyDown(event: KeyboardEvent): void {
    // Skip if typing in an input field
    if (this.isTypingTarget(event.target)) {
      return;
    }

    const key = event.key;

    // Toggle help
    if (key === '?' || (key === '/' && event.shiftKey)) {
      event.preventDefault();
      this.uiService.toggleHelp();
      return;
    }

    // Fit selection or all
    if (key === 'f' || key === 'F') {
      event.preventDefault();
      if (this.selectedNodeId) {
        this.viewerService.fitToSelection();
      } else {
        this.viewerService.fitToAll();
      }
      return;
    }

    // Fit all
    if (key === 'a' || key === 'A') {
      event.preventDefault();
      this.viewerService.fitToAll();
      return;
    }

    // Isolate selection
    if (key === 'i' || key === 'I') {
      if (this.selectedNodeId) {
        event.preventDefault();
        this.modelService.isolateSection(this.selectedNodeId);
        this.viewerService.fitToSelection();
      }
      return;
    }

    // Clear isolation
    if (key === 'Escape' || key === 'e' || key === 'E') {
      if (this.isolatedNodeId) {
        event.preventDefault();
        this.modelService.clearIsolation();
        this.viewerService.fitToAll();
      }
      return;
    }

    // Reset view
    if (key === 'r' || key === 'R') {
      event.preventDefault();
      this.viewerService.resetView();
      return;
    }
  }

  private isTypingTarget(target: EventTarget | null): boolean {
    if (!target) return false;
    const element = target as HTMLElement;
    const tag = (element.tagName || '').toLowerCase();
    return tag === 'input' || tag === 'textarea' || element.isContentEditable;
  }
}
