// src/presentation/components/App.jsx
import React, { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import Toolbar from './Toolbar.jsx'
import TreeView from './TreeView.jsx'
import Viewport from './Viewport.jsx'
import StatusPanel from './StatusPanel.jsx'
import Hotkeys from './Hotkeys.jsx'
import { clearError } from '../../app/slices/modelSlice.js'
import ErrorBoundary from './ErrorBoundary.jsx'

export default function App () {
  const status = useSelector(s => s.model.status)
  const error = useSelector(s => s.model.error)
  const dispatch = useDispatch()

  useEffect(() => {
    if (status === 'error') {
      const t = setTimeout(() => dispatch(clearError()), 5000)
      return () => clearTimeout(t)
    }
  }, [status, dispatch])
  return (
    <div className='layout'>
      <Toolbar />
      <aside className='sidebar'>
        <TreeView />
      </aside>
      <main className='main'>
        <ErrorBoundary>
          <Viewport />
          <Hotkeys />
          <StatusPanel />
        </ErrorBoundary>
        {status === 'loading' && (
          <div className='overlay'>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <strong style={{ color: '#93c5fd' }}>Loading…</strong>
              <span style={{ opacity: 0.9 }}>Parsing model, please wait</span>
            </div>
          </div>
        )}
        {status === 'error' && (
          <div className='overlay'>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <strong style={{ color: '#fca5a5' }}>Error:</strong>
              <span style={{ opacity: 0.9 }}>{String(error)}</span>
              <button className='btn' style={{ marginLeft: 'auto' }} onClick={() => dispatch(clearError())}>×</button>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}

// src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subject, takeUntil } from 'rxjs';
import { ToolbarComponent } from './components/toolbar/toolbar.component';
import { ViewportComponent } from './components/viewport/viewport.component';
import { HotkeysComponent } from './components/hotkeys/hotkeys.component';
import { ModelService, ModelState } from './services/model.service';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, ToolbarComponent, ViewportComponent, HotkeysComponent],
  template: `
    <div class="layout">
      <app-toolbar></app-toolbar>
      <main class="main">
        <app-viewport></app-viewport>
        <app-hotkeys></app-hotkeys>
        
        @if (status === 'loading') {
          <div class="overlay">
            <div style="display: flex; align-items: center; gap: 8px;">
              <strong style="color: #93c5fd;">Loading…</strong>
              <span style="opacity: 0.9;">Parsing model, please wait</span>
            </div>
          </div>
        }
        
        @if (status === 'error') {
          <div class="overlay">
            <div style="display: flex; align-items: center; gap: 8px;">
              <strong style="color: #fca5a5;">Error:</strong>
              <span style="opacity: 0.9;">{{ error }}</span>
              <button class="btn" style="margin-left: auto;" (click)="clearError()">×</button>
            </div>
          </div>
        }
      </main>
    </div>
  `,
  styles: []
})
export class AppComponent implements OnInit, OnDestroy {
  status: string = 'idle';
  error: string | null = null;
  private destroy$ = new Subject<void>();
  private errorTimeout: any = null;

  constructor(private modelService: ModelService) {}

  ngOnInit(): void {
    this.modelService.state$
      .pipe(takeUntil(this.destroy$))
      .subscribe((state: ModelState) => {
        this.status = state.status;
        this.error = state.error;
        
        // Auto-clear error after 5 seconds
        if (state.status === 'error') {
          if (this.errorTimeout) {
            clearTimeout(this.errorTimeout);
          }
          this.errorTimeout = setTimeout(() => {
            this.modelService.clearError();
          }, 5000);
        }
      });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
    if (this.errorTimeout) {
      clearTimeout(this.errorTimeout);
    }
  }

  clearError(): void {
    this.modelService.clearError();
    if (this.errorTimeout) {
      clearTimeout(this.errorTimeout);
      this.errorTimeout = null;
    }
  }
}

<div class="app-shell">
  <div class="toolbar"><app-toolbar></app-toolbar></div>
  <aside class="sidebar">
    <h3>Sections</h3>
    <app-section-tree></app-section-tree>
  </aside>
  <main class="canvas">
    <app-viewer-canvas></app-viewer-canvas>
  </main>
</div>
